### ISSUE TITLE
1.0.x: engine_cart:regenerate fails during migrations

### ISSUE THREAD

**Issue by dunn** [samvera-labs/hyrax#1060]
### Descriptive summary

On the `1-0-stable` branch, `rake engine_cart:regenerate` fails during DB migrations.  Here's the end of the rake output:

```
== 20170525232405 CreateSearches: migrating ===================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:searches, {:id=>:integer})
   -> 0.0016s
== 20170525232405 CreateSearches: migrated (0.0018s) ==========================

== 20170525232406 CreateBookmarks: migrating ==================================
-- adapter_name()
   -> 0.0000s
-- adapter_name()
   -> 0.0000s
-- create_table(:bookmarks, {:id=>:integer})
   -> 0.0020s
== 20170525232406 CreateBookmarks: migrated (0.0023s) =========================

== 20170525232407 AddPolymorphicTypeToBookmarks: migrating ====================
== 20170525232407 AddPolymorphicTypeToBookmarks: migrated (0.0320s) ===========

== 20170525232431 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0010s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0005s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0007s
== 20170525232431 DeviseCreateUsers: migrated (0.0024s) =======================

== 20170525232438 AddDeviseGuestsToUsers: migrating ===========================
-- change_table(:users)
   -> 0.0007s
== 20170525232438 AddDeviseGuestsToUsers: migrated (0.0008s) ==================

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateVersionCommitters < ActiveRecord::Migration[4.2]
/Users/alex/clones/hyrax/.internal_test_app/db/migrate/20170525232524_create_version_committers.hyrax.rb:2:in `<top (required)>'
/Users/alex/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/alex/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateVersionCommitters < ActiveRecord::Migration[4.2]
/Users/alex/clones/hyrax/.internal_test_app/db/migrate/20170525232524_create_version_committers.hyrax.rb:2:in `<top (required)>'
/Users/alex/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/alex/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
rake aborted!
EngineCart failed on with: pid 80239 exit 1
/Users/alex/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/alex/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => engine_cart:regenerate => engine_cart:generate
(See full trace by running task with --trace)
```

### Steps to reproduce the behavior

1. `git checkout 1-0-stable`
1. `rm -rf .internal_test_app`
1. Apply https://github.com/samvera-labs/hyrax/pull/1059 if necessary in order for `bundle install` to succeed.
1. `bundle exec rake engine_cart:regenerate`

**Comment by mjgiarlo** [comment]
@dunn Thanks for reporting this! I suspect cherry-picking the commit from https://github.com/samvera-labs/hyrax/pull/834 into `1-0-stable` will fix this. Up to give that a shot?

**Comment by dunn** [comment]
https://github.com/samvera-labs/hyrax/pull/1061

**Comment by dunn** [comment]
Fixed by https://github.com/samvera-labs/hyrax/commit/0178c056e713fe666a4f73720022a7ca65969b88
