### ISSUE TITLE
Template doesn't work with Rails 5.1

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyrax#833]
```
        rake  active_fedora_noid_engine:install:migrations
Copied migration 20170425144127_create_minter_states.active_fedora_noid_engine.rb from active_fedora_noid_engine
Copied migration 20170425144128_rename_minter_state_random_to_rand.active_fedora_noid_engine.rb from active_fedora_noid_engine
      insert  config/application.rb
       rails    db:migrate
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateSearches < ActiveRecord::Migration[4.2]
/Users/jcoyne/workspace/advanced-hydra-camp/hyrax-with-iiif/db/migrate/20170425143948_create_searches.blacklight.rb:3:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateSearches < ActiveRecord::Migration[4.2]
/Users/jcoyne/workspace/advanced-hydra-camp/hyrax-with-iiif/db/migrate/20170425143948_create_searches.blacklight.rb:3:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
       rails    hyrax:workflow:load
rails aborted!
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: permission_templates: SELECT "permission_templates".* FROM "permission_templates"
bin/rails:4:in `require'
bin/rails:4:in `<main>'
SQLite3::SQLException: no such table: permission_templates
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => hyrax:workflow:load
(See full trace by running task with --trace)
```

**Comment by jcoyne** [comment]
This will first require changes to devise-guests and blacklight. Later we'll need to make changes to hyrax.

**Comment by jcoyne** [comment]
Fixed in devise-guests and https://github.com/rails/rails/issues/28878. Waiting on Rails 5.1.0.rc3 or final before we can fix blacklight.

**Comment by atz** [comment]
Looks like you already found https://github.com/projectblacklight/blacklight/pull/1579

**Comment by mjgiarlo** [comment]
@jcoyne Is this still an issue?
