### ISSUE TITLE
Multiple problems with batch upload form

### ISSUE THREAD

**Issue by mjgiarlo** [samvera-labs/hyrax#976]
I'm seeing at least two, possibly related, issues with the batch upload form (in both Hyrax and Hyku):

1. The requirements never go from :red_circle: to :white_check_mark:. (Javascript-related?)
1. When I add files to the form, the controls for adding titles and resource types per file never appear, and thus the form cannot submit, because titles are required. (Possibly also Javascript-related?)

Reported via Hyku Beta test, by @kerrybannen.

**Comment by mjgiarlo** [comment]
Whoever picks this up may find it useful to begin with the branch I started, which adds feature specs: https://github.com/projecthydra-labs/hyrax/pull/977

**Comment by andjsmit** [comment]
@mjgiarlo Could this be an issue with the AWS installation only - related to files not uploading? I'm seeing the check mark, title (Display Label) and Resource Type inputs for a local install on both Firefox and Chrome.

I went from Dashboard -> Works -> Create batch of works, then dropped three PNG files into the Drop files here. Is this the right form?

![batch upload](https://cloud.githubusercontent.com/assets/333335/26170681/459027d8-3b10-11e7-89a6-698e842ba9f5.png)

**Comment by andjsmit** [comment]
Ah, but wait. I do see it in a local Hyku install.
![batch_upload_hyku](https://cloud.githubusercontent.com/assets/333335/26171816/49d4511c-3b14-11e7-9c30-0800e81647e0.png)

**Comment by mjgiarlo** [comment]
@andjsmit Ah, this could be Hyku-only, for sure. Thanks for running this down.

**Comment by mjgiarlo** [comment]
How is this going, @andjsmit?

**Comment by mjgiarlo** [comment]
@jcoyne still an issue?

**Comment by atz** [comment]
Right now on local Hyrax, batch only delivers me 1 work instead of all 5, for example.

**Comment by mjgiarlo** [comment]
Still an issue then! Thanks, @atz

**Comment by mjgiarlo** [comment]
I'm not seeing the former problem with required tickmarks, but I am seeing the latter problem:

When I add files to the form, the controls for adding titles and resource types per file never appear, and thus the form cannot submit, because titles are required. (Possibly also Javascript-related?)

**Comment by mjgiarlo** [comment]
@atz With the `:async` adapter? Do you also see it with `:inline` or `:sidekiq`?

**Comment by atz** [comment]
Yeah, the default `queue_adapter` is `:async`.  Log reveals:
```
[ActiveJob] [CreateWorkJob] [10979a2b-8fe9-4d86-b5ff-63e2e18b666f] Error performing CreateWorkJob (Job ID: 10979a2b-8fe9-4d86-b5ff-63e2e18b666f) from Async(default) in 5173.61ms: ActiveRecord::StatementInvalid (SQLite3::BusyException: database is locked: UPDATE "curation_concerns_o
perations" SET "status" = ?, "updated_at" = ? WHERE "curation_concerns_operations"."id" = ?):
/Users/atz/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `block in each'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `loop'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:107:in `each'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `to_a'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:218:in `block (2 levels) in exec_query'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:209:in `block in exec_query'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/Users/atz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:208:in `exec_query'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:239:in `exec_delete'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:130:in `update'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `update'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/relation.rb:85:in `_update_record'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/persistence.rb:575:in `_update_record'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/locking/optimistic.rb:80:in `_update_record'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:292:in `_update_record'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:344:in `block in _update_record'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:825:in `_run_update_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:344:in `_update_record'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/timestamp.rb:107:in `_update_record'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/persistence.rb:563:in `create_or_update'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:336:in `block in create_or_update'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/callbacks.rb:336:in `create_or_update'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/persistence.rb:129:in `save'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/validations.rb:44:in `save'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/attribute_methods/dirty.rb:35:in `save'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:308:in `block (2 levels) in save'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:223:in `transaction'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:308:in `block in save'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:307:in `save'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/suppressor.rb:42:in `save'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/persistence.rb:285:in `block in update'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:384:in `block in with_transaction_returning_status'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
/Users/atz/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/persistence.rb:283:in `update'
/Users/atz/repos/hyrax/app/models/hyrax/operation.rb:74:in `performing!'
/Users/atz/repos/hyrax/app/jobs/create_work_job.rb:17:in `perform'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/activejob-5.1.1/lib/active_job/queue_adapters/async_adapter.rb:68:in `perform'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/atz/.rvm/gems/ruby-2.4.1/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

Looks like SQLite can't handle us.

**Comment by hannahfrost** [comment]
Just noting that currently on Hyku demo, the resource type and title edits are possible, but resource type is not getting set. Editing title note yet tested.

**Comment by mjgiarlo** [comment]
:point_up: @andjsmit

**Comment by andjsmit** [comment]
Thanks. I'll update my working code to see what has changed. So far, I have not been able to track down much other than the JS errors. I should probably ask for help or return to ready column next week.

**Comment by andjsmit** [comment]
As I have not come to any solution(s) at this point and will not have time available to look further for awhile, I'm going remove my assignment to this issue. Here are the 2 JS errors I did see, but have no solution for: 

`TypeError: $(...).browseEverything is not a function[Learn More]  browse_everything...`
`Error: See almond README: incorrect module build, no module name  almond....`

**Comment by mjgiarlo** [comment]
This is fixed.
